### ISSUE TITLE
NAME!!

### ISSUE THREAD

**Issue by BeardedGinger** [BeardedGinger/download-gate-gravityforms#4]
Gateway, Resources, Downloads, Gates, Access, Rope, Ribbon Cutting, Open, Grant, Lock, Key, Vault
Protect, Protection, Protected, Guard, Checkpoint

**Comment by imeson** [comment]
GravityForms Protected Download Gate

File Access Protection for GravityForms

**File Vault for GravityForms** 
_Protect download access with a required form fill_

**Open Sesame for GravityForms**
_Protected file Vault. Make your users fill out a form before gaining access to a download_

Great for capturing emails / leads with the reward of a whitepaper, case study, insider guide, tips sheet, etc.
